// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspection need a direct (non-pooled) connection; pgbouncer's
    // transaction pooling mode doesn't reliably support the DDL Migrate runs.
    // Runtime queries use DATABASE_URL (pooled) via the adapter in src/lib/prisma.ts instead.
    url: process.env["DIRECT_URL"],
  },
});
